apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersafe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cybersafe
  template:
    metadata:
      labels:
        app: cybersafe
    spec:
      containers:
      - name: cybersafe-app
        image: khanalb58/cybersafe-app:latest
        ports:
        - containerPort: 3000
